name: tests-auth
on:
  # only run on pull request of where auth service changes
  pull_request:
    paths:
      - 'auth/**'
jobs:
  # "build" name of the job
  build:
    # create a virtual machine
    runs-on: ubuntu-latest
    steps:
      # take all the code of project
      - uses: actions/checkout@v2
      - run: cd auth && npm install && npm run test:ci
