name: tests-orders
on:
  # only run on pull request of where auth service changes
  pull_request:
    paths:
      - 'orders/**'
jobs:
  build:
    # create a virtual machine
    runs-on: ubuntu-latest
    steps:
      # take all the code of project
      - uses: actions/checkout@v2
      - run: cd orders && npm install && npm run test:ci
